### ISSUE TITLE
没有生效

### ISSUE THREAD

**Issue by jeremy0519** [next-theme/hexo-next-three#13]
安装好npm包并在主题配置文件中配置好后并没有生效

**Comment by jeremy0519** [comment]
浏览器console里
<img width="687" alt="image" src="https://github.com/next-theme/hexo-next-three/assets/46999838/46176f47-10cb-492b-b369-559c606e9a78">

**Comment by stevenjoezhang** [comment]
我修复了一下，你更新试试 https://github.com/next-theme/hexo-next-three/commit/0a4dc10545299a9059d73a8e211e37958951cca1

**Comment by jeremy0519** [comment]
可以用了。谢谢
